package com.gome.ass.dao.logistics;

import java.util.List;

import com.gome.ass.entity.CrmService;

public interface CrmServiceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_service
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_service
     *
     * @mbggenerated
     */
    int insert(CrmService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_service
     *
     * @mbggenerated
     */
    int insertSelective(CrmService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_service
     *
     * @mbggenerated
     */
    CrmService selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_service
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CrmService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_service
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CrmService record);
    
    
    void insertBatch(List<CrmService> cmServices);
    
	void deleteByJlorderCode(String jlorderCodes);
}