package com.gome.ass.entity;

public class CrmAccessories {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_accessories.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_accessories.accessories_prod_code
     *
     * @mbggenerated
     */
    private String accessoriesProdCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_accessories.accessories_prod_name
     *
     * @mbggenerated
     */
    private String accessoriesProdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_accessories.quantity
     *
     * @mbggenerated
     */
    private String quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_accessories.unit_price
     *
     * @mbggenerated
     */
    private String unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_accessories.amount
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_accessories.accessories_brand
     *
     * @mbggenerated
     */
    private String accessoriesBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_accessories.accessories_category
     *
     * @mbggenerated
     */
    private String accessoriesCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_accessories.leg_no
     *
     * @mbggenerated
     */
    private String legNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_accessories.install_bill_id
     *
     * @mbggenerated
     */
    private String installBillId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_accessories.id
     *
     * @return the value of crm_accessories.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_accessories.id
     *
     * @param id the value for crm_accessories.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_accessories.accessories_prod_code
     *
     * @return the value of crm_accessories.accessories_prod_code
     *
     * @mbggenerated
     */
    public String getAccessoriesProdCode() {
        return accessoriesProdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_accessories.accessories_prod_code
     *
     * @param accessoriesProdCode the value for crm_accessories.accessories_prod_code
     *
     * @mbggenerated
     */
    public void setAccessoriesProdCode(String accessoriesProdCode) {
        this.accessoriesProdCode = accessoriesProdCode == null ? null : accessoriesProdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_accessories.accessories_prod_name
     *
     * @return the value of crm_accessories.accessories_prod_name
     *
     * @mbggenerated
     */
    public String getAccessoriesProdName() {
        return accessoriesProdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_accessories.accessories_prod_name
     *
     * @param accessoriesProdName the value for crm_accessories.accessories_prod_name
     *
     * @mbggenerated
     */
    public void setAccessoriesProdName(String accessoriesProdName) {
        this.accessoriesProdName = accessoriesProdName == null ? null : accessoriesProdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_accessories.quantity
     *
     * @return the value of crm_accessories.quantity
     *
     * @mbggenerated
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_accessories.quantity
     *
     * @param quantity the value for crm_accessories.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(String quantity) {
        this.quantity = quantity == null ? null : quantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_accessories.unit_price
     *
     * @return the value of crm_accessories.unit_price
     *
     * @mbggenerated
     */
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_accessories.unit_price
     *
     * @param unitPrice the value for crm_accessories.unit_price
     *
     * @mbggenerated
     */
    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice == null ? null : unitPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_accessories.amount
     *
     * @return the value of crm_accessories.amount
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_accessories.amount
     *
     * @param amount the value for crm_accessories.amount
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_accessories.accessories_brand
     *
     * @return the value of crm_accessories.accessories_brand
     *
     * @mbggenerated
     */
    public String getAccessoriesBrand() {
        return accessoriesBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_accessories.accessories_brand
     *
     * @param accessoriesBrand the value for crm_accessories.accessories_brand
     *
     * @mbggenerated
     */
    public void setAccessoriesBrand(String accessoriesBrand) {
        this.accessoriesBrand = accessoriesBrand == null ? null : accessoriesBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_accessories.accessories_category
     *
     * @return the value of crm_accessories.accessories_category
     *
     * @mbggenerated
     */
    public String getAccessoriesCategory() {
        return accessoriesCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_accessories.accessories_category
     *
     * @param accessoriesCategory the value for crm_accessories.accessories_category
     *
     * @mbggenerated
     */
    public void setAccessoriesCategory(String accessoriesCategory) {
        this.accessoriesCategory = accessoriesCategory == null ? null : accessoriesCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_accessories.leg_no
     *
     * @return the value of crm_accessories.leg_no
     *
     * @mbggenerated
     */
    public String getLegNo() {
        return legNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_accessories.leg_no
     *
     * @param legNo the value for crm_accessories.leg_no
     *
     * @mbggenerated
     */
    public void setLegNo(String legNo) {
        this.legNo = legNo == null ? null : legNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_accessories.install_bill_id
     *
     * @return the value of crm_accessories.install_bill_id
     *
     * @mbggenerated
     */
    public String getInstallBillId() {
        return installBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_accessories.install_bill_id
     *
     * @param installBillId the value for crm_accessories.install_bill_id
     *
     * @mbggenerated
     */
    public void setInstallBillId(String installBillId) {
        this.installBillId = installBillId == null ? null : installBillId.trim();
    }
}