package com.gome.ass.entity;

public class CrmAccessoryBasicdata {
	private String id;

	private String websiteCode;

	private String companyCode;

	private String accessoryCode;

	private String shortText;
	private String accessoryPrice;

	private String timestampFrom;

	private String timestampTo;
	private String unit;

	private String updateFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column crm_accessory_basicdata.id
	 * 
	 * @return the value of crm_accessory_basicdata.id
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column crm_accessory_basicdata.id
	 * 
	 * @param id
	 *            the value for crm_accessory_basicdata.id
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column crm_accessory_basicdata.website_code
	 * 
	 * @return the value of crm_accessory_basicdata.website_code
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public String getWebsiteCode() {
		return websiteCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column crm_accessory_basicdata.website_code
	 * 
	 * @param websiteCode
	 *            the value for crm_accessory_basicdata.website_code
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public void setWebsiteCode(String websiteCode) {
		this.websiteCode = websiteCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column crm_accessory_basicdata.company_code
	 * 
	 * @return the value of crm_accessory_basicdata.company_code
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column crm_accessory_basicdata.company_code
	 * 
	 * @param companyCode
	 *            the value for crm_accessory_basicdata.company_code
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column crm_accessory_basicdata.accessory_code
	 * 
	 * @return the value of crm_accessory_basicdata.accessory_code
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public String getAccessoryCode() {
		return accessoryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column crm_accessory_basicdata.accessory_code
	 * 
	 * @param accessoryCode
	 *            the value for crm_accessory_basicdata.accessory_code
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public void setAccessoryCode(String accessoryCode) {
		this.accessoryCode = accessoryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column crm_accessory_basicdata.short_text
	 * 
	 * @return the value of crm_accessory_basicdata.short_text
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public String getShortText() {
		return shortText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column crm_accessory_basicdata.short_text
	 * 
	 * @param shortText
	 *            the value for crm_accessory_basicdata.short_text
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public void setShortText(String shortText) {
		this.shortText = shortText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column crm_accessory_basicdata.accessory_price
	 * 
	 * @return the value of crm_accessory_basicdata.accessory_price
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public String getAccessoryPrice() {
		return accessoryPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column crm_accessory_basicdata.accessory_price
	 * 
	 * @param accessoryPrice
	 *            the value for crm_accessory_basicdata.accessory_price
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public void setAccessoryPrice(String accessoryPrice) {
		this.accessoryPrice = accessoryPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column crm_accessory_basicdata.timestamp_from
	 * 
	 * @return the value of crm_accessory_basicdata.timestamp_from
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public String getTimestampFrom() {
		return timestampFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column crm_accessory_basicdata.timestamp_from
	 * 
	 * @param timestampFrom
	 *            the value for crm_accessory_basicdata.timestamp_from
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public void setTimestampFrom(String timestampFrom) {
		this.timestampFrom = timestampFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column crm_accessory_basicdata.timestamp_to
	 * 
	 * @return the value of crm_accessory_basicdata.timestamp_to
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public String getTimestampTo() {
		return timestampTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column crm_accessory_basicdata.timestamp_to
	 * 
	 * @param timestampTo
	 *            the value for crm_accessory_basicdata.timestamp_to
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public void setTimestampTo(String timestampTo) {
		this.timestampTo = timestampTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column crm_accessory_basicdata.unit
	 * 
	 * @return the value of crm_accessory_basicdata.unit
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column crm_accessory_basicdata.unit
	 * 
	 * @param unit
	 *            the value for crm_accessory_basicdata.unit
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column crm_accessory_basicdata.update_flag
	 * 
	 * @return the value of crm_accessory_basicdata.update_flag
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public String getUpdateFlag() {
		return updateFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column crm_accessory_basicdata.update_flag
	 * 
	 * @param updateFlag
	 *            the value for crm_accessory_basicdata.update_flag
	 * 
	 * @mbggenerated Thu Oct 23 09:42:33 CST 2014
	 */
	public void setUpdateFlag(String updateFlag) {
		this.updateFlag = updateFlag;
	}
	
	@Override
	public boolean equals(Object o){
		if(this == o){
			return true;
		}else{
			if(o instanceof CrmAccessoryBasicdata){
				CrmAccessoryBasicdata obj = (CrmAccessoryBasicdata)o;
				if(obj.getAccessoryCode().endsWith(this.getAccessoryCode())){
					return true;
				} else{
					return false;
				}
			}
			return false;
		}
	}
	
	@Override
	public int hashCode(){
		 int result = 17;  //任意素数   
		 result = this.getAccessoryCode().hashCode() * 37;
		 result = this.getShortText().hashCode() * 17 + result;
		 return result;   
	}
}