package com.gome.ass.entity;

public class CrmCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_company.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_company.company_code
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_company.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_company.street
     *
     * @mbggenerated
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_company.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_company.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_company.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_company.remarks2
     *
     * @mbggenerated
     */
    private String remarks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_company.remarks3
     *
     * @mbggenerated
     */
    private String remarks3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_company.remarks4
     *
     * @mbggenerated
     */
    private String remarks4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_company.id
     *
     * @return the value of crm_company.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_company.id
     *
     * @param id the value for crm_company.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_company.company_code
     *
     * @return the value of crm_company.company_code
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_company.company_code
     *
     * @param companyCode the value for crm_company.company_code
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_company.company_name
     *
     * @return the value of crm_company.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_company.company_name
     *
     * @param companyName the value for crm_company.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_company.street
     *
     * @return the value of crm_company.street
     *
     * @mbggenerated
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_company.street
     *
     * @param street the value for crm_company.street
     *
     * @mbggenerated
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_company.city
     *
     * @return the value of crm_company.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_company.city
     *
     * @param city the value for crm_company.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_company.province
     *
     * @return the value of crm_company.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_company.province
     *
     * @param province the value for crm_company.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_company.remarks1
     *
     * @return the value of crm_company.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_company.remarks1
     *
     * @param remarks1 the value for crm_company.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_company.remarks2
     *
     * @return the value of crm_company.remarks2
     *
     * @mbggenerated
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_company.remarks2
     *
     * @param remarks2 the value for crm_company.remarks2
     *
     * @mbggenerated
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_company.remarks3
     *
     * @return the value of crm_company.remarks3
     *
     * @mbggenerated
     */
    public String getRemarks3() {
        return remarks3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_company.remarks3
     *
     * @param remarks3 the value for crm_company.remarks3
     *
     * @mbggenerated
     */
    public void setRemarks3(String remarks3) {
        this.remarks3 = remarks3 == null ? null : remarks3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_company.remarks4
     *
     * @return the value of crm_company.remarks4
     *
     * @mbggenerated
     */
    public String getRemarks4() {
        return remarks4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_company.remarks4
     *
     * @param remarks4 the value for crm_company.remarks4
     *
     * @mbggenerated
     */
    public void setRemarks4(String remarks4) {
        this.remarks4 = remarks4 == null ? null : remarks4.trim();
    }
}