package com.gome.ass.entity;

import java.util.Date;

public class JlAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.id
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.account_number
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private String accountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.account_name
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.account_password
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private String accountPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.company_code
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.account_dept
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private String accountDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.website_code
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private String websiteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.website_name
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private String websiteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.start_date
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.end_date
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.status
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.init_password
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private Date initPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.account_status
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    private Long accountStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.id
     *
     * @return the value of jl_account.id
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.id
     *
     * @param id the value for jl_account.id
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.account_number
     *
     * @return the value of jl_account.account_number
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.account_number
     *
     * @param accountNumber the value for jl_account.account_number
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.account_name
     *
     * @return the value of jl_account.account_name
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.account_name
     *
     * @param accountName the value for jl_account.account_name
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.account_password
     *
     * @return the value of jl_account.account_password
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public String getAccountPassword() {
        return accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.account_password
     *
     * @param accountPassword the value for jl_account.account_password
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.company_code
     *
     * @return the value of jl_account.company_code
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.company_code
     *
     * @param companyCode the value for jl_account.company_code
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.account_dept
     *
     * @return the value of jl_account.account_dept
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public String getAccountDept() {
        return accountDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.account_dept
     *
     * @param accountDept the value for jl_account.account_dept
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setAccountDept(String accountDept) {
        this.accountDept = accountDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.website_code
     *
     * @return the value of jl_account.website_code
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public String getWebsiteCode() {
        return websiteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.website_code
     *
     * @param websiteCode the value for jl_account.website_code
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setWebsiteCode(String websiteCode) {
        this.websiteCode = websiteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.website_name
     *
     * @return the value of jl_account.website_name
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public String getWebsiteName() {
        return websiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.website_name
     *
     * @param websiteName the value for jl_account.website_name
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setWebsiteName(String websiteName) {
        this.websiteName = websiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.start_date
     *
     * @return the value of jl_account.start_date
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.start_date
     *
     * @param startDate the value for jl_account.start_date
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.end_date
     *
     * @return the value of jl_account.end_date
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.end_date
     *
     * @param endDate the value for jl_account.end_date
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.status
     *
     * @return the value of jl_account.status
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.status
     *
     * @param status the value for jl_account.status
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.init_password
     *
     * @return the value of jl_account.init_password
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public Date getInitPassword() {
        return initPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.init_password
     *
     * @param initPassword the value for jl_account.init_password
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setInitPassword(Date initPassword) {
        this.initPassword = initPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.account_status
     *
     * @return the value of jl_account.account_status
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public Long getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.account_status
     *
     * @param accountStatus the value for jl_account.account_status
     *
     * @mbggenerated Mon Sep 22 10:41:51 CST 2014
     */
    public void setAccountStatus(Long accountStatus) {
        this.accountStatus = accountStatus;
    }
}