package com.gome.ass.entity;

public class ShRoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_role_menu.role_id
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_role_menu.role_name
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_role_menu.resource_id
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_role_menu.role_type
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    private String roleType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_role_menu.role_id
     *
     * @return the value of v_role_menu.role_id
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_role_menu.role_id
     *
     * @param roleId the value for v_role_menu.role_id
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_role_menu.role_name
     *
     * @return the value of v_role_menu.role_name
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_role_menu.role_name
     *
     * @param roleName the value for v_role_menu.role_name
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_role_menu.resource_id
     *
     * @return the value of v_role_menu.resource_id
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_role_menu.resource_id
     *
     * @param resourceId the value for v_role_menu.resource_id
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_role_menu.role_type
     *
     * @return the value of v_role_menu.role_type
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_role_menu.role_type
     *
     * @param roleType the value for v_role_menu.role_type
     *
     * @mbggenerated Thu Oct 30 10:04:11 CST 2014
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }
}