package com.gome.ass.entity;

public class ShUserPwdInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_user_pwd_info.user_id
     *
     * @mbggenerated Thu Sep 25 10:37:03 CST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_user_pwd_info.password
     *
     * @mbggenerated Thu Sep 25 10:37:03 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sh_user_pwd_info.user_type
     *
     * @mbggenerated Thu Sep 25 10:37:03 CST 2014
     */
    private Integer userType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_user_pwd_info.user_id
     *
     * @return the value of sh_user_pwd_info.user_id
     *
     * @mbggenerated Thu Sep 25 10:37:03 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_user_pwd_info.user_id
     *
     * @param userId the value for sh_user_pwd_info.user_id
     *
     * @mbggenerated Thu Sep 25 10:37:03 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_user_pwd_info.password
     *
     * @return the value of sh_user_pwd_info.password
     *
     * @mbggenerated Thu Sep 25 10:37:03 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_user_pwd_info.password
     *
     * @param password the value for sh_user_pwd_info.password
     *
     * @mbggenerated Thu Sep 25 10:37:03 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sh_user_pwd_info.user_type
     *
     * @return the value of sh_user_pwd_info.user_type
     *
     * @mbggenerated Thu Sep 25 10:37:03 CST 2014
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sh_user_pwd_info.user_type
     *
     * @param userType the value for sh_user_pwd_info.user_type
     *
     * @mbggenerated Thu Sep 25 10:37:03 CST 2014
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }
}