package com.gome.ass.entity;

public class CrmService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_service.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_service.service_measures_code
     *
     * @mbggenerated
     */
    private String serviceMeasuresCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_service.service_measures_name
     *
     * @mbggenerated
     */
    private String serviceMeasuresName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_service.quantity
     *
     * @mbggenerated
     */
    private String quantity;
    
    private String unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_service.gross_value
     *
     * @mbggenerated
     */
    private String grossValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_service.leg_no
     *
     * @mbggenerated
     */
    private String legNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_service.install_bill_id
     *
     * @mbggenerated
     */
    private String installBillId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_service.id
     *
     * @return the value of crm_service.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_service.id
     *
     * @param id the value for crm_service.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_service.service_measures_code
     *
     * @return the value of crm_service.service_measures_code
     *
     * @mbggenerated
     */
    public String getServiceMeasuresCode() {
        return serviceMeasuresCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_service.service_measures_code
     *
     * @param serviceMeasuresCode the value for crm_service.service_measures_code
     *
     * @mbggenerated
     */
    public void setServiceMeasuresCode(String serviceMeasuresCode) {
        this.serviceMeasuresCode = serviceMeasuresCode == null ? null : serviceMeasuresCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_service.service_measures_name
     *
     * @return the value of crm_service.service_measures_name
     *
     * @mbggenerated
     */
    public String getServiceMeasuresName() {
        return serviceMeasuresName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_service.service_measures_name
     *
     * @param serviceMeasuresName the value for crm_service.service_measures_name
     *
     * @mbggenerated
     */
    public void setServiceMeasuresName(String serviceMeasuresName) {
        this.serviceMeasuresName = serviceMeasuresName == null ? null : serviceMeasuresName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_service.quantity
     *
     * @return the value of crm_service.quantity
     *
     * @mbggenerated
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_service.quantity
     *
     * @param quantity the value for crm_service.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(String quantity) {
        this.quantity = quantity == null ? null : quantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_service.gross_value
     *
     * @return the value of crm_service.gross_value
     *
     * @mbggenerated
     */
    public String getGrossValue() {
        return grossValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_service.gross_value
     *
     * @param grossValue the value for crm_service.gross_value
     *
     * @mbggenerated
     */
    public void setGrossValue(String grossValue) {
        this.grossValue = grossValue == null ? null : grossValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_service.leg_no
     *
     * @return the value of crm_service.leg_no
     *
     * @mbggenerated
     */
    public String getLegNo() {
        return legNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_service.leg_no
     *
     * @param legNo the value for crm_service.leg_no
     *
     * @mbggenerated
     */
    public void setLegNo(String legNo) {
        this.legNo = legNo == null ? null : legNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_service.install_bill_id
     *
     * @return the value of crm_service.install_bill_id
     *
     * @mbggenerated
     */
    public String getInstallBillId() {
        return installBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_service.install_bill_id
     *
     * @param installBillId the value for crm_service.install_bill_id
     *
     * @mbggenerated
     */
    public void setInstallBillId(String installBillId) {
        this.installBillId = installBillId == null ? null : installBillId.trim();
    }

	public String getUnitPrice() {
		return unitPrice;
	}

	public void setUnitPrice(String unitPrice) {
		this.unitPrice = unitPrice;
	}
    
}