package com.gome.ass.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.8
 * 2014-06-04T19:12:42.197+08:00
 * Generated source version: 2.5.8
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "wmgwSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WmgwSoap {
    /**
     * 短信息发送接口
     */
    @WebResult(name = "MongateCsSpSendSmsNewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MongateCsSpSendSmsNew", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MongateCsSpSendSmsNew")
    @WebMethod(operationName = "MongateCsSpSendSmsNew", action = "http://tempuri.org/MongateCsSpSendSmsNew")
    @ResponseWrapper(localName = "MongateCsSpSendSmsNewResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MongateCsSpSendSmsNewResponse")
    public java.lang.String mongateCsSpSendSmsNew(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "pszMobis", targetNamespace = "http://tempuri.org/")
        java.lang.String pszMobis,
        @WebParam(name = "pszMsg", targetNamespace = "http://tempuri.org/")
        java.lang.String pszMsg,
        @WebParam(name = "iMobiCount", targetNamespace = "http://tempuri.org/")
        int iMobiCount,
        @WebParam(name = "pszSubPort", targetNamespace = "http://tempuri.org/")
        java.lang.String pszSubPort
    );


}
